### ISSUE TITLE
Computing Effect Size from blavaan models

### ISSUE THREAD

**Issue by JulianGaviriaL** [easystats/effectsize#420] opened 2022-03-03 12:59 UTC
Hello,

First, thanks a lot for such a great work with easystats!

How can I compute the effect size of the regressions from the following blavaan model?

A part of trying with:
```
> effectsize(fitModel.a1.bayes)
Warning: Unable to varify if response should not be standardized.
Response will be standardized.
Error in if (m_info$is_bayesian) { : argument is of length zero
In addition: Warning messages:
1: Could not access model information. 
2: Could not access model information
```

I also tried with the output of the "describe_posterior" function (bayestestR package):

```
> effectsize(res.m1_4net_beh_bayes)
Error: A data frame is no valid object for this function.
```

These are the script of the model and the attached data:
[data_ent_C5_combo.txt](https://github.com/easystats/effectsize/files/8177926/data_ent_C5_combo.txt)

```
d <- read.delim("data_ent_C5_combo.txt")

d[, c(2:5, 18:21)] <- d[, c(2:5, 18:21)] / 10

theModel.aim1 <- "
  # Behavioral LV Measurement Model
[data_ent_C5_combo.txt](https://github.com/easystats/effectsize/files/8177838/data_ent_C5_combo.txt)

  task.beh.aff =~ 1*aff_cC + b2*aff_iC + b3*aff_iI + b4*aff_cI # Behavioral LV definitions
  task.beh.neu =~ 1*neu_cC + b2*neu_iC + b3*neu_iI + b4*neu_cI
  
  task.beh.aff ~~ task.beh.aff # Behavioral LV variances and covariances
  task.beh.neu ~~ task.beh.neu
  task.beh.aff ~~ task.beh.neu
  
  aff_cC ~~ e1.a*aff_cC # Behavioral MV residuals
  aff_iC ~~ e2.a*aff_iC
  aff_iI ~~ e3.a*aff_iI
  aff_cI ~~ e4.a*aff_cI
  neu_cC ~~ e1.n*neu_cC
  neu_iC ~~ e2.n*neu_iC
  neu_iI ~~ e3.n*neu_iI
  neu_cI ~~ e4.n*neu_cI

  aff_cC ~ m1.a*1 # Behavioral MV means
  aff_iC ~ m2.a*1
  aff_iI ~ m3.a*1
  aff_cI ~ m4.a*1
  neu_cC ~ m1.n*1
  neu_iC ~ m2.n*1
  neu_iI ~ m3.n*1
  neu_cI ~ m4.n*1

  # Brain Means and Covariances
  PA_1 ~~ e1.r.a*PA_1 # Brain MV residuals
  PA_2 ~~ e2.r.a*PA_2
  PA_3 ~~ e3.r.a*PA_3
  PA_4 ~~ e4.r.a*PA_4
  TA_1 ~~ e1.t.a*TA_1
  TA_2 ~~ e2.t.a*TA_2
  TA_3 ~~ e3.t.a*TA_3
  TA_4 ~~ e4.t.a*TA_4
  PN_1 ~~ e1.r.n*PN_1
  PN_2 ~~ e2.r.n*PN_2
  PN_3 ~~ e3.r.n*PN_3
  PN_4 ~~ e4.r.n*PN_4
  TN_1 ~~ e1.t.n*TN_1
  TN_2 ~~ e2.t.n*TN_2
  TN_3 ~~ e3.t.n*TN_3
  TN_4 ~~ e4.t.n*TN_4

  PA_1 ~~ PN_1 # Inter-context covariances
  PA_2 ~~ PN_2
  PA_3 ~~ PN_3
  PA_4 ~~ PN_4
  TA_1 ~~ TN_1
  TA_2 ~~ TN_2
  TA_3 ~~ TN_3
  TA_4 ~~ TN_4

  PA_1 ~ m1.r.a*1 # Brain MV means
  PA_2 ~ m2.r.a*1
  PA_3 ~ m3.r.a*1
  PA_4 ~ m4.r.a*1
  TA_1 ~ m1.t.a*1
  TA_2 ~ m2.t.a*1
  TA_3 ~ m3.t.a*1
  TA_4 ~ m4.t.a*1
  PN_1 ~ m1.r.n*1
  PN_2 ~ m2.r.n*1
  PN_3 ~ m3.r.n*1
  PN_4 ~ m4.r.n*1
  TN_1 ~ m1.t.n*1
  TN_2 ~ m2.t.n*1
  TN_3 ~ m3.t.n*1
  TN_4 ~ m4.t.n*1

  # Structural Model
  task.beh.aff ~ PA_1 + PA_2 + PA_3 + PA_4
  TA_1 ~ PA_1 + PA_2 + PA_3 + PA_4 + task.beh.aff
  TA_2 ~ PA_1 + PA_2 + PA_3 + PA_4 + task.beh.aff
  TA_3 ~ PA_1 + PA_2 + PA_3 + PA_4 + task.beh.aff
  TA_4 ~ PA_1 + PA_2 + PA_3 + PA_4 + task.beh.aff
  
  task.beh.neu ~ PN_1 + PN_2 + PN_3 + PN_4
  TN_1 ~ PN_1 + PN_2 + PN_3 + PN_4 + task.beh.neu
  TN_2 ~ PN_1 + PN_2 + PN_3 + PN_4 + task.beh.neu
  TN_3 ~ PN_1 + PN_2 + PN_3 + PN_4 + task.beh.neu
  TN_4 ~ PN_1 + PN_2 + PN_3 + PN_4 + task.beh.neu

fitModel.a1.bayes <- blavaan(theModel.aim1, data=d, n.chains=1, burnin=1000, sample=5000, bcontrol=list(cores=4))

```
"

Thanks in advance for your comments. 

Best,
Julian

**Comment by mattansb** [comment] 2022-03-03 13:14
What effect size are you looking for?

If you are looking for standardized estimates, you can do this directly in `blavaan`:

```R
# Get standardized draws
zpost <- standardizedPosterior(fitModel.a1.bayes)
zpost <- as.data.frame(zpost)

# Then pass the draw to bayestestR:
bayestestR::describe_posterior(zpost)
```

Alternatively, you can fit the model with pre-standardized data (but note that you will also have to adjust any scale invariant priors!!!):

```R
dz <- effectsize::standardize(d)
fitModel.a1.bayes <- blavaan(theModel.aim1, data=dz, n.chains=1, burnin=1000, sample=5000, bcontrol=list(cores=4))
```

**Comment by strengejacke** [comment] 2022-03-03 14:28
`model_parameters()` also works, and you can - similar to `describe_posterior()` - add some relevant tests (relevant in a Bayesian context), see help page: https://easystats.github.io/parameters/reference/model_parameters.stanreg.html

``` r
parameters::model_parameters(fit)
parameters::model_parameters(as.data.frame(standardizedPosterior(fit)))
```

**Comment by JulianGaviriaL** [comment] 2022-03-04 21:55
Thanks a lot for your quick response.and apologies in case I was not clear enough. 

I aim to calculate the "cohen d" for each regression of my model "fitModel.a1.bayes". Of course I initially tried with the "describe_posterior" function (bayestestR), given the amount of (standardized) indices it provides. Great job!
```
describe_posterior(fitModel.a1.bayes,
                                                centrality = "all",
                                                dispersion = TRUE,
                                                ci = 0.95,
                                                ci_method = "hdi",
                                                effects = "all", 
                                                test = c("p_direction", "p_significance", "rope", "equitest"))
```
However, it seems I'm not using the appropriate function for computing the Cohen's d effect size.

Many thanks in advance for any hint...

**Comment by JulianGaviriaL** [comment] 2022-03-05 10:00
Perhaps I overlooked the information from https://easystats.github.io/effectsize/articles/bayesian_models.html
According to this site, the predictive role of the variables (i.e., effect size) is quantified by the standardized median. Right? If so, then I wonder whether the obtained values would require a conversion that facilitate their interpretation. The results from
`parameters::model_parameters(as.data.frame(standardizedPosterior(fitModel.a1.bayes)))
`
yielded  Media=0.45 even for some regressions with pd > 99.9% and 0% in ROPE  (see attached file).
[res.fitModel.a1.bayes.xlsx](https://github.com/easystats/effectsize/files/8190405/res.fitModel.a1.bayes.xlsx)

**Comment by mattansb** [comment] 2022-03-05 11:39
> I aim to calculate the "cohen d" for each regression of my model

I'm not sure that makes a whole lot of sense - Cohen's *d* is most applicable to compare means between two groups - it is less applicable for continuous predictors (which is the case here), nor is a measure of fit for a whole regression.

[The vignette](https://easystats.github.io/effectsize/articles/bayesian_models.html) describes how to estimate standardized coefficients for regression models, which is also what `bayestestR::describe_posterior(as.data.frame(standardizedPosterior(fitModel.a1.bayes)))` gives you.

I'm not sure what else you would need.

**Comment by bwiernik** [comment] 2022-03-06 18:56
If you want something on a standardized scale that is comparable to Cohen's d for all predictors, continuous and categorical, you can follow the instructions to obtain standardized coefficients above and set the `two_sd` argument to `TRUE`

**Comment by mattansb** [comment] 2022-03-07 11:52
Closing this, as I think we addressed the question (:

**Closed by mattansb** 2022-03-07 11:52 UTC

**Comment by JulianGaviriaL** [comment] 2022-03-08 17:59
Thanks a lot for the hints. 
Just wonder how to debug the following errors:

```
standardize_posteriors(fitModel.a1.bayes, method = "refit", two_sd = TRUE)

Warning: Unable to varify if response should not be standardized.
Response will be standardized.
Error in if (m_info$is_bayesian) { : argument is of length zero
In addition: Warning messages:
1: Could not access model information. 
2: Could not access model information.
```
I get the same output  when  the model is fitted with pre-standardized data:

```
dz <- effectsize::standardize(d)
fitModel.a1.bayes <- blavaan(theModel.aim1, data=dz, n.chains=1, burnin=1000, sample=5000, bcontrol=list(cores=4))
```
As @bwiernik commented, I'm looking for something on a standardized scale comparable/similar  to Cohen's d for all predictors in a bayesian SEM context. 

Again, thank you very much for your comments.

**Comment by mattansb** [comment] 2022-03-09 08:28
Yes, `standardize_posteriors(method = "refit")` calls `standardize()`, so if the latter doesn't work neither will the former.

Getting `two_sd` to correctly do what you (@bwiernik) intend it to do is tricky because some of the predictors in some of the regressions in @JulianGaviriaL's model are also themselves outcomes in other regressions.
