### ISSUE TITLE
Date variable trips up standardize()

### ISSUE THREAD

**Issue by IsadoraBM** [easystats/effectsize#300] opened 2021-02-28 02:07 UTC
"Error in !info$is_linear : invalid argument type" when running standardize() on a tibble (converted to as.data.frame and issue persised). Removing the `date` format variable took care of the issue.

**Comment by IndrajeetPatil** [comment] 2021-02-28 09:03
Can you please provide a reprex (https://reprex.tidyverse.org/) so that we can reproduce this?

**Comment by mattansb** [comment] 2021-02-28 09:10
Dates are now ignored by default, unless `force = TRUE` (similar to factors). 
I don't know if this is the preferable behavior? Should dates just be converted to numeric anyway? I don't use dates, so if anyone has an opinion...

``` r
d <- data.frame(
  date = as.Date(c("02/27/92", "02/27/92", "01/14/92"), "%m/%d/%y")
)

effectsize:::standardize(d)
#>         date
#> 1 1992-02-27
#> 2 1992-02-27
#> 3 1992-01-14

effectsize:::standardize(d, force = TRUE)
#>         date
#> 1  0.5773503
#> 2  0.5773503
#> 3 -1.1547005
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment] 2021-02-28 09:47
I would suggest to ignore dates. Because standardising Dates makes no sense.

**Comment by mattansb** [comment] 2021-02-28 11:43
Then I am closing this.

Thanks @IsadoraBM for catching this!

**Closed** 2021-02-28 16:48 UTC
Labels: bug 🐜
