### ISSUE TITLE
Adding SE to the output (can be an attribute)

### ISSUE THREAD

**Issue by Generalized** [easystats/effectsize#583] opened 2023-04-07 12:32 UTC
Calculation of a confidence interval for an effect size under multiple imputation needs to pass both the estimate and its standard error to the Rubin's pooling rule (optionally after some transformation, like Fisher's z). Currently, to get the SE of some effect size, like rank biserial (https://github.com/easystats/effectsize/blob/main/R/rank_diff.R ) I have to back-transform the estimate and either of the CI ends and divide add/subtract them and / by appropriate quantile. Would you consider adding the raw SE in the output of these functions? If you don't want to add additional field to the output, maybe just add an attribute? It will be "transparent", won't break the current data structure returned by these functions, but facilitate a lot pooling these quantities under the MICE framework.

```
> set.seed(1000)
> x1 <- rnorm(20, mean=3)
> x2 <- rnorm(60, mean=3.8)

> (rb <- effectsize::rank_biserial(x1, x2))
r (rank biserial) |         95% CI
----------------------------------
-0.69             | [-0.82, -0.50]

> (SE <- (atanh(rb$CI_high) - atanh(rb$r_rank_biserial)) / qnorm(0.975))
[1] 0.15

> tanh(atanh(rb$r_rank_biserial) + c(-1, 1) * stats::qnorm(0.975) * SE)
[1] -0.8151 -0.5035
```

**Comment by mattansb** [comment] 2023-04-08 12:00
This is a duplicate of #425.

**Closed by mattansb** 2023-04-08 12:00 UTC
Labels: duplicate 👯‍♂️

**Comment by bwiernik** [comment] 2023-04-08 13:38
For this purpose, we probably also want to compute an effective N and use that for the ncp degrees of freedom
